### ISSUE TITLE
Crash after pipeline going NULL state (v1.2.1)

### ISSUE THREAD

**Issue by NoobsEnslaver** [go-gst/go-gst#123]
Env:
- `uname -a
Linux stealth 6.8.0-40-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 10:34:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- gstreamer version: 1.24.2
- go-gst: v1.2.1

After updating go-gst from v1.1.0 to v1.2.1 got this crash after terminating pipeline:

```
double free or corruption (fasttop)
SIGABRT: abort
PC=0x700381c9eb1c m=8 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 77 gp=0xc0003a6380 m=8 mp=0xc00018a008 [syscall, locked to thread]:
runtime.cgocall(0xc4ef50, 0xc000351bf8)
	runtime/cgocall.go:157 +0x5b fp=0xc000351bd0 sp=0xc000351b98 pc=0x42727b
github.com/mattn/go-pointer._Cfunc_free(0x7002f0056560)
	_cgo_gotypes.go:51 +0x3f fp=0xc000351bf8 sp=0xc000351bd0 pc=0xa5bf9f
github.com/mattn/go-pointer.Unref.func1(0x7002f0056560)
	github.com/mattn/go-pointer@v0.0.1/pointer.go:56 +0x45 fp=0xc000351c28 sp=0xc000351bf8 pc=0xa5c3a5
github.com/mattn/go-pointer.Unref(0x7002f0056560)
	github.com/mattn/go-pointer@v0.0.1/pointer.go:56 +0x7b fp=0xc000351c50 sp=0xc000351c28 pc=0xa5c31b
github.com/go-gst/go-gst/gst.goUnrefGopointerUserData(...)
	github.com/go-gst/go-gst@v1.1.0/gst/cgo_exports.go:282
_cgoexp_67dd6ebedcda_goUnrefGopointerUserData(0x700331fffbd0)
	_cgo_gotypes.go:18257 +0x36 fp=0xc000351c68 sp=0xc000351c50 pc=0xa98a96
runtime.cgocallbackg1(0xa98a60, 0x700331fffbd0, 0x0)
	runtime/cgocall.go:403 +0x2b7 fp=0xc000351d28 sp=0xc000351c68 pc=0x4279d7
runtime.cgocallbackg(0xa98a60, 0x700331fffbd0, 0x0)
	runtime/cgocall.go:322 +0x136 fp=0xc000351da0 sp=0xc000351d28 pc=0x427676
runtime.cgocallbackg(0xa98a60, 0x700331fffbd0, 0x0)
	<autogenerated>:1 +0x29 fp=0xc000351dc8 sp=0xc000351da0 pc=0x49c7c9
runtime.cgocallback(0xc000351e28, 0x4272a5, 0xc3b070)
	runtime/asm_amd64.s:1079 +0xcc fp=0xc000351df0 sp=0xc000351dc8 pc=0x49998c
runtime.systemstack_switch()
	runtime/asm_amd64.s:474 +0x8 fp=0xc000351e00 sp=0xc000351df0 pc=0x497bc8
runtime.cgocall(0xc3b070, 0xc000351e60)
	runtime/cgocall.go:175 +0x85 fp=0xc000351e38 sp=0xc000351e00 pc=0x4272a5
github.com/go-gst/go-glib/glib._Cfunc_g_main_loop_run(0x70032c001160)
	_cgo_gotypes.go:2730 +0x3f fp=0xc000351e60 sp=0xc000351e38 pc=0xa5f01f
git.xxxx.ru/media/xxxx/gstreamer.Init.func1.(*MainLoop).Run.1(0xc0001b1328)
	github.com/go-gst/go-glib@v1.2.1/glib/gmainloop.go:53 +0x54 fp=0xc000351ea0 sp=0xc000351e60 pc=0xaa3cb4
github.com/go-gst/go-glib/glib.(*MainLoop).Run(...)
	github.com/go-gst/go-glib@v1.2.1/glib/gmainloop.go:53
```

trying to got minimal reproduce example, if i do - send here.
In gstreamer it self logs (GST_DEBUG=4 - nothing special, only INFO logs, no errors)

P.S.
Found something: https://github.com/RSWilli/go-gst-issue-94/pull/1

**Comment by RSWilli** [comment]
from the provided reproduction I get different results:

```
malloc_consolidate(): unaligned fastbin chunk detected
```

or

```
(issue94:185038): GLib-GObject-CRITICAL **: 15:59:04.961: object_ref: assertion '!object_already_finalized' failed

(issue94:185038): GLib-GObject-CRITICAL **: 15:59:04.962: instance with invalid (NULL) class pointer

(issue94:185038): GLib-GObject-CRITICAL **: 15:59:04.962: signal_emit_valist_unlocked: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(issue94:185038): GLib-GObject-CRITICAL **: 15:59:04.962: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

or

```
malloc(): unaligned tcache chunk detected
```

This seems to be a race condition. The results change when I use the debugger vs without, and also when the `time.Sleep` is used or not.

Could you look more into this and provide a more reproducible code snippet, please?

**Comment by RSWilli** [comment]
I ran the program with `gdb`, and got the following stack trace for the crashing thread:

```
Thread 56 "udpsrc_rtcp:src" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffecffff6c0 (LWP 18590)]
Downloading source file /usr/src/debug/glibc/glibc/malloc/malloc.c
0x00007ffff787efc9 in tcache_get_n (tc_idx=<optimized out>, ep=<optimized out>) at malloc.c:3186                                                                           
3186          *ep = REVEAL_PTR (e->next);
(gdb) stack bt full
Undefined command: "stack".  Try "help".
(gdb) bt full
#0  0x00007ffff787efc9 in tcache_get_n (tc_idx=<optimized out>, ep=<optimized out>) at malloc.c:3186
        e = 0x7fffc80094f0
        e = <optimized out>
#1  tcache_get (tc_idx=<optimized out>) at malloc.c:3199
#2  __GI___libc_malloc (bytes=bytes@entry=65) at malloc.c:3320
        ar_ptr = <optimized out>
        victim = <optimized out>
        tbytes = <optimized out>
        tc_idx = <optimized out>
        __PRETTY_FUNCTION__ = "__libc_malloc"
#3  0x00007ffff7d59e4b in g_malloc (n_bytes=65) at ../glib/glib/gmem.c:100
        mem = <optimized out>
#4  0x00007ffff7d7025b in g_strdup (str=0x7fff7c0a5910 "3ca992322c8c344525e9db7d07b8546844c38a7dc0f2f1e5bf8b296b73f42849") at ../glib/glib/gstrfuncs.c:323
--Type <RET> for more, q to quit, c to continue without paging--
        __n = 65
        __s = 1
        __p = <optimized out>
        new_str = <optimized out>
        length = 65
#5  0x00007ffff7c71953 in gst_element_decorate_stream_id_internal (element=element@entry=0x7fff840f9660, stream_id=stream_id@entry=0x0)
    at /usr/include/glib-2.0/glib/gstrfuncs.h:321
        query = 0x7ffec8001b90
        uri = 0x7fff84101370 "ѫ\3717\371\177"
        cs = <optimized out>
        upstream_event = <optimized out>
        upstream_stream_id = <optimized out>
        new_stream_id = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        sinkpad = <optimized out>
        __func__ = "gst_element_decorate_stream_id_internal"
#6  0x00007ffff7c71c57 in gst_pad_create_stream_id_internal (pad=<optimized out>, parent=parent@entry=0x7fff840f9660, stream_id=stream_id@entry=0x0)
    at ../gstreamer/subprojects/gstreamer/gst/gstutils.c:4240
        __func__ = "gst_pad_create_stream_id_internal"
#7  0x00007ffff7c71e39 in gst_pad_create_stream_id (pad=<optimized out>, parent=parent@entry=0x7fff840f9660, stream_id=stream_id@entry=0x0)
    at ../gstreamer/subprojects/gstreamer/gst/gstutils.c:4350
#8  0x00007fffb0093746 in gst_base_src_send_stream_start.part.0.isra.0 (src=0x7fff840f9660) at ../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasesrc.c:986
        stream_id = <optimized out>
        event = <optimized out>
        ret = <optimized out>
        __func__ = {<optimized out> <repeats 31 times>}
#9  0x00007fffb00775f8 in gst_base_src_send_stream_start (src=0x7fff840f9660) at ../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasesrc.c:3161
        ret = 1
        ret = <optimized out>
        __func__ = {<optimized out> <repeats 31 times>}
        stream_id = <optimized out>
        event = <optimized out>
        _g_boolean_var_44 = <optimized out>
#10 gst_base_src_loop (pad=0x7fff840f7170) at ../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasesrc.c:2907
        src = 0x7fff840f9660
        buf = 0x0
        ret = <optimized out>
        position = <optimized out>
        eos = 0
        blocksize = <optimized out>
        pending_events = 0x0
        tmp = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        __func__ = "gst_base_src_loop"
#11 0x00007ffff7c56685 in gst_task_func (task=0x7fff8410b630) at ../gstreamer/subprojects/gstreamer/gst/gsttask.c:399
        lock = 0x7fff840f71e0
        tself = <optimized out>
        priv = <optimized out>
        __func__ = "gst_task_func"
#12 0x00007ffff7d8a373 in g_thread_pool_thread_proxy (data=<optimized out>) at ../glib/glib/gthreadpool.c:336
        task = 0x7fff840f76a0
        pool = 0x7fff740138e0
#13 0x00007ffff7d841b6 in g_thread_proxy (data=0x7fff5c003a90) at ../glib/glib/gthread.c:835
        thread = 0x7fff5c003a90
        __func__ = "g_thread_proxy"
#14 0x00007ffff786e39d in start_thread (arg=<optimized out>) at pthread_create.c:447
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140732388079296, 2561304827793741906, 140732388079296, -128, 0, 140735047252896, 2561304827781158994, 2560830586418337874}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#15 0x00007ffff78f349c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

I read this as "the streaming thread of udpsrc crashed"

To me this rather looks like a bug in gstreamer itself instead of a bug in the bindings. I could be wrong though. @sdroege what do you think?

**Comment by biglittlebigben** [comment]
We are hitting what looks like the same issue. In our case, this reproduces 100% of the case with go-gst v1.2.1 and v1.2.0, but not v1.1.0

**Comment by biglittlebigben** [comment]
git dissect seems to indicate that this was introduced with https://github.com/go-gst/go-gst/commit/1f33aa3c9d1e96cfc78e9f6c7c08ea0f4cf420c2

**Comment by biglittlebigben** [comment]
Looking for feedback on https://github.com/go-gst/go-gst/pull/126 and https://github.com/go-gst/go-gst/pull/127

**Comment by RSWilli** [comment]
@NoobsEnslaver please close this issue if the linked PRs fixed this issue

**Comment by NoobsEnslaver** [comment]
Thanks for reaction. Yes, now it's looks good - no crashes, no leaks
