### ISSUE TITLE
proxysink/proxysrc usage

### ISSUE THREAD

**Issue by inve1** [go-gst/go-gst#41]
Hey there, I'm trying to use the `proxysink` and `proxysrc` elements. [Reading the C example,](https://gstreamer.freedesktop.org/documentation/proxy/proxysrc.html?gi-language=c) it looks like this should work (I've seen a similar python example as well)

```go
	sp := p.sourceStr + " ! proxysink name=psink"
	p.logger.Info("source pipe description ", sp)
	sourcePipe, sourceErr := gst.NewPipelineFromString(sp)
	if sourceErr != nil {
		p.logger.WithError(sourceErr).Error("source error")
		return nil, sourceErr
	}
	psink, _ := sourcePipe.GetElementByName("psink")

       //  p.pSrc is pipe2.GetElementByName("psrc")

	setErr := p.pSrc.SetProperty("proxysink", psink)
	if setErr != nil {
		p.logger.WithError(setErr).Fatal("failed setting property")
		return nil, setErr
	}
```

but this crashes:

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 15 [running]:
github.com/go-gst/go-glib/glib.(*Value).SetPointer.func1(0x140000126d0, 0x140000126c8)
        /Users/<snip>/vendor/github.com/go-gst/go-glib/glib/gvalue.go:557 +0x44
github.com/go-gst/go-glib/glib.(*Value).SetPointer(0x140000126d0, 0x140000126c8)
        /Users/<snip>/vendor/github.com/go-gst/go-glib/glib/gvalue.go:557 +0x24
github.com/go-gst/go-glib/glib.gValue({0x102fad240, 0x140000126c8})
        /Users/<snip>/vendor/github.com/go-gst/go-glib/glib/gvalue.go:284 +0x1194
github.com/go-gst/go-glib/glib.(*Object).SetProperty(0x140000125f0, {0x102d2f9b5, 0x9}, {0x102fad240, 0x140000126c8})
        /Users/<snip>/vendor/github.com/go-gst/go-glib/glib/gobject.go:215 +0xdc
gitlab.ocado.tech/advanced-technology/production/webcam_pipeline/gstreamer_pipeline.(*gstPipeline).createSource(0x14000116500)
        /Users/<snip>/gstreamer_pipeline/gst.go:166 +0x2c4
.....
Exiting.
```

after some fiddling, I got it to work with this workaround and the pipelines play correctly

```go
	sp := p.sourceStr + " ! proxysink name=psink"
	p.logger.Info("source pipe description ", sp)
	sourcePipe, sourceErr := gst.NewPipelineFromString(sp)
	if sourceErr != nil {
		p.logger.WithError(sourceErr).Error("source error")
		return nil, sourceErr
	}
	psink, _ := sourcePipe.GetElementByName("psink")

	proxySink := psink.GObject()
       //  p.pSrc is pipe2.GetElementByName("psrc")
	propertyType, _ := p.pSrc.GetPropertyType("proxysink")

	val, typeErr := glib.ValueInit(propertyType)
	if typeErr != nil {
		p.logger.WithError(typeErr).Fatal("whew")
		return nil, typeErr
	}

	val.SetInstance(proxySink.Native())
	setErr := p.pSrc.SetPropertyValue("proxysink", val)
	if setErr != nil {
		p.logger.WithError(setErr).Fatal("failed setting property")
		return nil, setErr
	}
```

Doing that works, but if I stop (set the state to NULL) the initial pipeline (the one with `proxysink`) and call `Clear` on it (which I need to do to handle camera malfunctions) and it goes out of scope in go I get this warning

```
(<unknown>:70460): GLib-GObject-CRITICAL **: 21:56:01.223: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

which sometimes panics the program

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0xafd4e8709de77de3 pc=0x105a3ba14]

runtime stack:
runtime.throw({0x104eda852?, 0x105146780?})
        /opt/homebrew/opt/go/libexec/src/runtime/panic.go:1047 +0x40 fp=0x16f8dae50 sp=0x16f8dae20 pc=0x1045af9c0
runtime.sigpanic()
        /opt/homebrew/opt/go/libexec/src/runtime/signal_unix.go:825 +0x20c fp=0x16f8dae80 sp=0x16f8dae50 pc=0x1045c67dc

goroutine 3 [syscall]:
runtime.cgocall(0x104e816e0, 0x1400007bd08)
        /opt/homebrew/opt/go/libexec/src/runtime/cgocall.go:157 +0x54 fp=0x1400007bcd0 sp=0x1400007bc90 pc=0x10457b294
github.com/go-gst/go-glib/glib._Cfunc_g_object_unref(0x14e6b5590)
        _cgo_gotypes.go:3588 +0x34 fp=0x1400007bd00 sp=0x1400007bcd0 pc=0x104c69824
github.com/go-gst/go-glib/glib.(*Object).Unref.func1(0x140003a40c8)
        /Users/<snip>/vendor/github.com/go-gst/go-glib/glib/gobject.go:141 +0x4c fp=0x1400007bd40 sp=0x1400007bd00 pc=0x104c7649c
github.com/go-gst/go-glib/glib.(*Object).Unref(0x140003a40c8)
        /Users/<snip>/vendor/github.com/go-gst/go-glib/glib/gobject.go:141 +0x20 fp=0x1400007bd60 sp=0x1400007bd40 pc=0x104c76430
runtime.call16(0x0, 0x105146630, 0x14000122060, 0x10, 0x10, 0x10, 0x1400007be40)
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:478 +0x78 fp=0x1400007bd80 sp=0x1400007bd60 pc=0x1045e1988
runtime.runfinq()
        /opt/homebrew/opt/go/libexec/src/runtime/mfinal.go:255 +0x3d8 fp=0x1400007bfd0 sp=0x1400007bd80 pc=0x104590548
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400007bfd0 sp=0x1400007bfd0 pc=0x1045e3a74
created by runtime.createfing
        /opt/homebrew/opt/go/libexec/src/runtime/mfinal.go:163 +0x4c
```

Any ideas if I'm doing something wrong? cheers

**Comment by RSWilli** [comment]
coming back to this after a while

> setErr := p.pSrc.SetProperty("proxysink", psink)

this line sets a `gst.Element`as a property. This was a bug fixed in #65 . Your first code snippet should work fine now.

At first glance I can see nothing wrong with the workaround snippet, although the "sometimes crashes" makes me wonder if this is a GC related early free of an object.

#62 and #61 fixed this Issue. TLDR: the pointer returned by Native() could get invalidated by the GC.

If the problem still happens on the new version then please create another issue.
