### ISSUE TITLE
Handle up- and downcasting safely

### ISSUE THREAD

**Issue by RSWilli** [go-gst/go-gst#80]
This takes #79 and generalizes it.

We need to add some methods to convert the objects safely between the type hierarchie. E.g. a call to `gst_element_get_static_pad` always returns a `GstPad` aka `*gst.Pad`, but in some cases (e.g. bins) these pads are actually a `GstGhostPad`, and currently there is no safe way to convert them for the go application.

Similarly, `gst_parse_launch` returns a `GstElement`, but oftentimes a pipeline or bin is needed.

This is also be relevant for glib signals (see https://github.com/go-gst/go-gst/discussions/77#discussioncomment-9099011) where we unmarshal elements and sometimes do not have unmarshaler for every plugin, e.g. `GstMpegAudioParse`, but in other times we need to downcast an unmarshaled `*gst.Element` to a `*gst.Object` because the signal handler expects it that way.

**Comment by RSWilli** [comment]
@neilyoung I was not able to reproduce the signal unmarshaling panic you produced in #77, could you provide a small reproduction please? I tried the following and did not get a panic:

```go
package main

import (
	"time"

	"github.com/go-gst/go-glib/glib"
	"github.com/go-gst/go-gst/gst"
)

func main() {
	gst.Init(nil)
	pipeline, err := gst.NewPipelineFromString("audiotestsrc ! lamemp3enc ! decodebin ! fakesink")

	if err != nil {
		panic(err)
	}

	decodebin, err := pipeline.GetElementByName("decodebin0")

	if err != nil {
		panic(err)
	}

	decodebin.Connect("child-added", func(decodebin *gst.Element, child *glib.Object, name string) {
		println("Child added:", name)
	})

	pipeline.SetState(gst.StatePlaying)

	mainLoop := glib.NewMainLoop(glib.MainContextDefault(), false)

	defer mainLoop.Quit()

	go func() {
		t := time.NewTicker(5 * time.Second)

		for {
			select {
			case <-t.C:
				pipeline.DebugBinToDotFile(gst.DebugGraphShowAll, "pipeline")
				return
			}
		}
	}()

	mainLoop.Run()
}
```

**Comment by neilyoung** [comment]
OK, let's checkout the original Python code, since there is a potential recursion: My pipeline has several "decodebin" elements.

```
    def decodebin_child_added(self, child_proxy, Object, name, user_data):
        self.log.info(f"Decodebin child added: {name}")
        if name.find("decodebin") != -1:
            Object.connect("child-added", self.decodebin_child_added, user_data)


nbin = Gst.Bin.new("source-bin-00")
uri_decode_bin = Gst.ElementFactory.make("uridecodebin", None)
uri_decode_bin.connect("child-added", self.decodebin_child_added, nbin)

```

Since it is an NVIDIA pipeline, it will be hard to give you an example, which works for you w/o having the NVIDIA elements...

**Comment by neilyoung** [comment]
My pipeline:  nvstreammux -> nvinfer -> nvtracker -> nvmultistreamtiler -> nvvideoconvert -> nvdsosd -> nvvideoconvert -> capsfilter -> nvv4l2h264enc -> rtspclientsink

**Comment by neilyoung** [comment]
This one panics on my AWS instance, but it doesn't contain special NVIDIA components.

You should be able to reproduce:


```
package main

import (
	"strings"

	"github.com/go-gst/go-glib/glib"
	"github.com/go-gst/go-gst/gst"
)

func childAdded(self *gst.Element, child *glib.Object, name string) {
	println("child-added", name)
	if strings.Contains(name, "decodebin") {
		child.Connect("child-added", childAdded)
	}
}

func main() {
	gst.Init(nil)
	pipeline, err := gst.NewPipelineFromString("uridecodebin ! audioconvert ! audioresample ! autoaudiosink")

	if err != nil {
		panic(err)
	}

	uriDecodeBin, err := pipeline.GetElementByName("uridecodebin0")
	if err != nil {
		panic(err)
	}
	
	
	uriDecodeBin.Connect("child-added", childAdded)
	uriDecodeBin.SetProperty("uri", "https://gstreamer.freedesktop.org/data/media/sintel_trailer-480p.webm")
	
	pipeline.SetState(gst.StatePlaying)

	mainLoop := glib.NewMainLoop(glib.MainContextDefault(), false)

	defer mainLoop.Quit()

	mainLoop.Run()
}

```

Full log:

```
ubuntu@ai:~/gotest1$ go run main.go
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
warning: no suitable Go value from object for arg 1: missing marshaler for type: GstSoupHTTPSrc
child-added source
warning: no suitable Go value from object for arg 1: missing marshaler for type: GstTypeFindElement
child-added typefindelement0
warning: no suitable Go value from object for arg 1: missing marshaler for type: GstDecodeBin
child-added decodebin0
warning: no suitable Go value from object for arg 1: missing marshaler for type: GstQueue2
child-added queue2-0
warning: no suitable Go value from object for arg 0: missing marshaler for type: GstDecodeBin
panic: reflect.Value.Convert: value of type *glib.Object cannot be converted to type *gst.Element

goroutine 18 [running, locked to thread]:
reflect.Value.Convert({0x53a460?, 0xc0000460a8?, 0x554318?}, {0x578d60, 0x545420})
	/usr/local/go/src/reflect/value.go:3368 +0x12c
github.com/go-gst/go-glib/glib.goMarshal(0x425ca8?, 0x0, 0x3, 0x7f63a67faa50, 0x0?, 0x484101?)
	/home/ubuntu/go/pkg/mod/github.com/go-gst/go-glib@v1.0.1/glib/glib.go:257 +0x4a9
exit status 2
ub
```

**Comment by RSWilli** [comment]
@neilyoung got your example working with the current bindings, this should help you solve your problem until the bindings are fixed:

```go
// ------------------v
func childAdded(self any, child *glib.Object, name string) {
	println("child-added", name)
	if strings.Contains(name, "decodebin") {
		child.Connect("child-added", childAdded)
	}
}
```

Explaination: the first argument sometimes is a `*glib.Object` instead of a `*gst.Element`, and this cannot be converted. There should be a better error message for this.

With the "fix" the logs look like this:

```
warning: no suitable Go value from object for arg 1: missing marshaler for type: GstCurlHttpSrc
child-added source
warning: no suitable Go value from object for arg 1: missing marshaler for type: GstTypeFindElement
child-added typefindelement0
warning: no suitable Go value from object for arg 1: missing marshaler for type: GstDecodeBin
child-added decodebin0
warning: no suitable Go value from object for arg 1: missing marshaler for type: GstQueue2
child-added queue2-0
warning: no suitable Go value from object for arg 0: missing marshaler for type: GstDecodeBin
warning: no suitable Go value from object for arg 1: missing marshaler for type: GstMatroskaDemux
child-added matroskademux0
warning: no suitable Go value from object for arg 0: missing marshaler for type: GstDecodeBin
warning: no suitable Go value from object for arg 1: missing marshaler for type: GstMultiQueue
child-added multiqueue0
warning: no suitable Go value from object for arg 0: missing marshaler for type: GstDecodeBin
warning: no suitable Go value from object for arg 1: missing marshaler for type: GstVP8Dec
child-added vp8dec0
warning: no suitable Go value from object for arg 0: missing marshaler for type: GstDecodeBin
warning: no suitable Go value from object for arg 1: missing marshaler for type: GstVorbisDec
child-added vorbisdec0
```

**Comment by neilyoung** [comment]
Yes, thanks a log for your assistance. This works well. Maybe there would be a way to suppress the warnings?

**Comment by RSWilli** [comment]
Yeah this is the matter of this issue, I'm trying to come up with a good way to handle these casts automatically.

I do have some Ideas, when I have some free time again I'll try them out.

**Comment by neilyoung** [comment]
No issue, I could live with it. If you are probably interested in "the last remaining problem" (sigh!) with this port, please have a look at this post. Maybe you have some good ideas. https://forums.developer.nvidia.com/t/trying-to-unmarshal-nvdsbatchmeta-in-golang-some-help-required/289579 The original Python code is here, there a module named PYDS is taking care of the marshalling/unmarshalling of the NVIDEA GSTBuffer content... https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/tree/master/apps/deepstream-rtsp-in-rtsp-out

But his is just in case you have some ideas. You don't have to mess with this, of course.

**Comment by RSWilli** [comment]
My current Idea consists of the following:

An interface that will be implemented by all extending structs:

```go
type CastableFromGlibObject interface {
    // this method must be callable on a null receiver, and will modify the receiver pointer so that it is the casted object
    // an error is returned if the cast fails
    FromGlibObject(obj *glib.Object) error
}
```

And a new method/function to perform the cast generically:

```go
func (g *glib.Object) As(target CastableFromGlibObject) error {
    // ...
} 
```

That way every object that embeds the `*glib.Object` can be casted to any other extending object, provided it passes the checks in the `FromGlibObject` method. My favorite way though would be to include generics somehow in this, but receivers cannot introduce new generic values, so this would have to be a standalone function...

I will iterate on this more

**Comment by RSWilli** [comment]
FYI: https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#No-parameterized-methods

**Comment by RSWilli** [comment]
To introduce generics the only way would be to do the following:

```go
type CastableFromGlibObject interface {
	// this method must be callable on a null receiver, and will
	// modify the receiver pointer so that it is the casted object
	// an error is returned if the cast fails
	FromGlibObject(obj *Object) error
}

// ExtendsGlibObject is an interface that is used to ensure that a type
// embeds a *Object and can be casted to another type
type ExtendsGlibObject interface {
	// asObject returns the underlying glib.Object
	asObject() *Object
}

func (v *Object) asObject() *Object {
	return v
}

func Cast[Target CastableFromGlibObject](obj ExtendsGlibObject) (Target, error) {
	var target Target
	err := target.FromGlibObject(obj.asObject())
	return target, err
}


// usage:
res, err := glib.Cast[*gst.Element](uriDecodeBin)
```

this way a cast to any extending type would be done by extracting the object, and calling `FromGlibObject`, which would internally handle the pointer type checks and casting with refcounting etc

**Comment by RSWilli** [comment]
@danjenkins what do you think, do you have any other ideas?

**Comment by RSWilli** [comment]
done in the generated bindings through the marshalers. This introduces some extra steps, but allows casting the interfaces the gopher way, without any extra function calls
